---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - acl
    - git

- name: Update apt
  become: yes
  apt: update_cache=yes

