---
# DB
#
# Installs DB choices, right now just PostgreSQL

- name: Install PostgreSQL
  apt: pkg={{ item}} update_cache=yes state=latest
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-contrib
    - libpq-dev
       