---
# This playbook deploys the whole application stack for
# developing and deploying RoR CRUD apps

- hosts: all
  connection: local
  become: yes
  become_user: root  
      
  roles:
    - common
    - web
    - db
    - framework
        