---
# COMMON
#
# role: common
# install items common to every setup 
 
 # Ensures apitutde is installed for initial package management
- name: Update all packages to the latest version
  apt:
    name: aptitude 
     
- name: Update apt repositories
  apt: 
    update_cache: yes
  ignore_errors: yes
        
- name: Safe system upgrade via aptitude
  apt: 
    upgrade: safe
  connection: local
  become: yes
  become_user: root  
  ignore_errors: yes
  
- name: Ensure basic tools and packages are present
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - git
    - curl
