---
# FRAMEWORK
#
# Load Ruby on Rails with version changer
#

# CHRUBY + RUBY-INSTALL

#------------------------------------------- 
# RUBY-INSTALL

# is ruby-install already present?

- name: check for existing ruby-install
  stat:
    path: "{{ ruby_install_exec_fullpath }}"
  register: result_a

# ruby-install version check
  
- name: check ruby-install version
  command: "{{ ruby_install_exec_fullpath }} --version"
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False

# steps to install the app  
  
- name: installation steps for ruby-install
  include: ruby-install-install.yml
  when: "not result_a.stat.exists or ruby_install_ver is not defined or ruby_install_ver not in result_b.stdout"

#------------------------------------------- 
# Ruby
  
- name: install ruby per the version in vars
  shell: "ruby-install ruby {{ ruby_ver }}"

#------------------------------------------- 
# chruby

# steps to install the app  
  
- name: installation steps for chruby
  include: chruby-install.yml

#------------------------------------------- 
# Rails
#- name: Install rails
#  shell: "gem install rails -v {{ rails_ver }} --no-rdoc --no-ri"
  
  
