---
# FRAMEWORK
#
# Load Ruby on Rails with version changer
#

# CHRUBY + RUBY-INSTALL

#------------------------------------------- 
# RUBY-INSTALL

# is ruby-install already present?

- name: check for existing ruby-install
  stat:
    path: "{{ ruby_install_exec_fullpath }}"
  register: result_a

# ruby-install version check
  
- name: check ruby-install version
  command: "{{ ruby_install_exec_fullpath }} --version"
  register: result_b
  when: "result_a.stat.exists"
  changed_when: False
  failed_when: False

# steps to install the app  
  
- name: installation steps for ruby-install
  include: ruby-install-install.yml
  when: "not result_a.stat.exists or ruby_install_ver is not defined or ruby_install_ver not in result_b.stdout"

#------------------------------------------- 
# Ruby

# TODO: check for existence before runninng this steps

- name: ruby version per var already installed
  stat:
    path: "/opt/rubies/ruby-{{ ruby_ver }}"
  register: result_ruby_main_ver
 
- name: install a version of ruby before chruby, if not already installed
  shell: "ruby-install ruby {{ ruby_ver }}" 
  when: not result_ruby_main_ver.stat.exists
   
#------------------------------------------- 
# chruby

# steps to install the app to switch between ruby versions
  
- name: installation steps for chruby
  include: chruby-install.yml

#------------------------------------------- 
# Ruby gems

- name: install ruby gems
  become_user: vagrant
  command: bash -lc "gem install --no-ri {{item}}" 
  with_items:
   - rails
  ignore_errors: yes

 