  # COMMON
  #
  # role: common
  # install items common to every setup
  
  tasks:
    - name: Get aptitude for upgrade
      apt: 
        name: apt
        state: latest
             
    - name: Update apt repositories
      apt: 
        update_cache: yes
            
    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Ensure basic tools and packages are present
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - git
        - curl
