#
#   DEVELOPMENT PLAYBOOK
#
#
#   Local Host at 192.168.33.10
#   (All hosts?)
#
#   Aptitude
#   System upgrades
#
#   Apache 
#
#   Bash, OpenSSL, etc updates
#
#   PostgreSQL
#   
#   Git
#   Curl
#
#   Ruby
#   Rails
#
#   PostgreSQL
#   
#   
#
---
- hosts: all
  connection: local
  become: yes
  become_user: root  
  
  vars:
    - rbenv_root: /home/vagrant/.rbenv
    - ruby_deploy_user: vagrant 
    - ruby_version: 2.6.0
    
  tasks:
  
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present
      
    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Ensure basic tools and packages are present
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - git
        - curl
      
    - name: Install Apache
      apt: name=apache2 state=latest update_cache=yes
            
    - name: Start Apache
      service: name=apache2 state=running enabled=yes
              
    - name: Install PostgreSQL
      apt: pkg={{ item}} update_cache=yes state=latest
      with_items:
        - python-psycopg2
        - postgresql
        - postgresql-contrib
        - libpq-dev
       
 
    #------------------- RUBY ON RAILS
    
    # ruby-build is packaged with my Ubuntu, but
    # it builds ruby from scratch.  Opting for more direct way    

    - name: Ruby on Rails dependencies
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - build-essential      
        - libssl-dev
        - libssl-doc
        - libcurl4-openssl-dev
        - libmysqlclient-dev
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        
    - name: Clone rbenv repository
      git: repo=https://github.com/rbenv/rbenv.git
           dest=~{{ rbenv_root }}
           update=no           

    - name: Creates plugin directory for rbenv
      file: path={{ rbenv_root }}/plugins/ owner={{ ruby_deploy_user }} group={{ ruby_deploy_user }} mode=0755 state=directory

    # TODO: install any desired rbenv plugins
      
    - name: Add rbenv to PATH in bashrc
      command: echo 'export PATH="{{ rbenv_root }}/bin:$PATH"' >> ~/.bashrc    
      
    - name: Add to bashrc an rbenv init      
      command: echo 'eval "$(rbenv init -)"' >> ~/.bashrc
     
    - name: Install ruby with rbenv
      shell: echo 'export PATH="{{ rbenv_root }}/bin:$PATH"' rbenv install {{ ruby_version }}
      


       