#
#   DEVELOPMENT PLAYBOOK
#
#
#   Local Host at 192.168.33.10
#   (All hosts?)
#
#   Aptitude
#   System upgrades
#
#   Apache 
#
#   Bash, OpenSSL, etc updates
#
#   PostgreSQL
#   
#   Git
#   Curl
#
#   Ruby
#   Rails
#
#   PostgreSQL
#   
#   
#
---
- hosts: all
  connection: local
  become: yes
  become_user: root  
      
  tasks:
              
    - name: Update apt repositories
      apt: 
        update_cache: yes
            
    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Ensure basic tools and packages are present
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - git
        - curl
      
    - name: Install Apache
      apt: name=apache2 state=latest update_cache=yes
            
    - name: Start Apache
      service: name=apache2 state=running enabled=yes
              
    - name: Install PostgreSQL
      apt: pkg={{ item}} update_cache=yes state=latest
      with_items:
        - python-psycopg2
        - postgresql
        - postgresql-contrib
        - libpq-dev
       
 