---
- hosts: local
  connection: local
  become: yes
  become_user: root
  
#- hosts: rails
#  remote_user: root
#  become: yes

#
#   DEVELOPMENT PLAYBOOK
#
#
#   Local Host at 192.168.33.10
#   (All hosts?)
#
#   Aptitude
#   System upgrades
#
#   Apache 
#   
#   Git
#   Curl
#
#   Ruby
#   Rails
#
#   PostgreSQL
#   
#   
#
  
  
  tasks:
  
    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present
      
    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
      tags: packages
      
    - name: Install Apache
      apt: name=apache2 state=latest update_cache=yes
            
    - name: Start Apache
      service: name=apache2 state=running enabled=yes
      
#    # TODO: make index.php file:  <?php echo "Hello World">
#    - name: Install Hello World PHP script
#      copy: src=index.php dest=/var/www/html/index.php mode=0664

    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - git
        - curl
      
    - name: Install PostgreSQL
      apt: name={{ item}} update_cache=true state=installed
      with_items:
        - python-psycopg2
        - postgresql
        - postgresql-contrib
        - libpq-dev
      tags: packages
      
    - name: PostgreSQL running
      service: name=postgresql state=started enabled=yes
      
    # TODO: create the database
            
    # TODO: instally buy
    
#    - hosts: rails
#      remote_user: root
#      become: yes
#      tasks:
#        - name: Update all packages to the latest version
#          apt:
#            upgrade: dist